site_name: wknk-doc-python
site_author: wasknk    
repo_url: https://github.com/YourUsername/YourRepoName 

theme:
    name: readthedocs      
    highlightjs: true       

nav:
    - 首页: 'index.md'      
    - 脚本教程指南: 'guide.md' 
    - Docker Usage: 'docker.md'
    - Alembic: 'alembic.md'
    - Jupyter Notebook: 'JupyterNotebook.md'
    - Git: 'git.md'
    - Wsl: 'wsl.md'
    - Wraps: 'wraps.md'
    - Poetry: 'poetry.md'
    - Pip: 'pip.md'
    - Uvicorn: 'uvicorn.md'
    - Copier: 'copier.md'
    - Type-hints: 'type-hints.md'
    - Rich: 'rich.md'
    - Annotated: 'Annotated.md'
    - Flask: 'Flask.md'
    - Uv: 'uv.md'
    - Gunicorn: 'gunicorn.md'
    - pip-tools: 'pip-tools.md'
    - pyproject.toml: 'pyproject.toml.md'
    - docker-compose: 'docker-compose.md'
    - asyncio: 'asyncio.md'
    - redis: 'redis.md'
    - aioredis: 'aioredis.md'
    - pytest: 'pytest.md'
    - pytest-cov: 'pytest-cov.md'
    - pytest-xdist: 'pytest-xdist.md'

    #- Celery: 'celery.md'